### ISSUE TITLE
Hex view contents of section?

### ISSUE THREAD

**Issue by phatpaul** [gsmrana/Hex-File-Analyzer#1]
Nice looking tool.
Can I use it to view the contents of the .text section in a .elf as a hex viewer would show?

**Comment by gsmrana** [comment]
You can save the file as a hex file using this tool then open it to view the hex content. Thanks!
![Elf-File-Analyzer-hex-view](https://user-images.githubusercontent.com/51051655/117536338-4a79c800-b01c-11eb-9bca-321d5c30fd5c.png)

**Comment by phatpaul** [comment]
Thanks for the reply.  That seems to have worked.

But how would I know I'm only looking at the .text section of the elf?  Is that implied by the SaveAs to hex?
